theme: jekyll-theme-cayman
lang: fr-FR
title: BattleQuiz
google_analytics: UA-42170580-4
description: La nouvelle app de quiz compÃ©titif pour briller en sociÃ©tÃ© ! ğŸ˜
github:
  is_project_page: false
